package com.assessment.tracker.server.persistence.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import java.util.*;
import com.assessment.tracker.server.persistence.entities.logging.*;

import com.assessment.tracker.server.utils.enums.*;

@Entity
@Table(name = "users")

// table for users, refer to data design doc for reference
public class User {

    // first section for generating columns
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID userID; // primary key

    @OneToMany
    private Set<AssignedUser> assignedUsers = new HashSet<>();

    @Column(nullable = false, unique = true)
    private String username;

    @Column(nullable = false, unique = true)
    private String email;// format verification?

    @JsonIgnore
    @Column(nullable = false, unique = true)
    private String password; // required encryption

    @OneToMany(mappedBy = "setter")
    private List<Assessment> setterFor;

    @OneToMany(mappedBy = "checker")
    private List<Assessment> checkerFor;

    @OneToMany(mappedBy = "user")
    private List<Log> actionsTaken;

    @Column(nullable = false, unique = false)
    private UserType userType;

    @OneToMany(mappedBy = "targetUser")
    private List<UserLog> logs;

    // constructors
    public User(String username, String email, String Password, UserType userType) {
        this.username = username;
        this.password = Password;
        this.email = email;
        this.userType = userType;
    }

    public User() {
    }

    // the following section for getters and setter (auto-generated by IDE)

    public void setUserID(UUID userID) {
        this.userID = userID;
    }

    public List<Assessment> getSetterFor() {
        return setterFor;
    }

    public void setSetterFor(List<Assessment> setterFor) {
        this.setterFor = setterFor;
    }

    public List<Assessment> getCheckerFor() {
        return checkerFor;
    }

    public void setCheckerFor(List<Assessment> checkerFor) {
        this.checkerFor = checkerFor;
    }

    public List<Log> getActionsTaken() {
        return actionsTaken;
    }

    public void setActionsTaken(List<Log> actionsTaken) {
        this.actionsTaken = actionsTaken;
    }

    public UUID getUserID() {
        return userID;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public UserType getUserType() {
        return userType;
    }

    public void setUserType(UserType userType) {
        this.userType = userType;
    }

}
