spring.application.name=server

springdoc.api-docs.path=/swagger-ui.html

# DB Setup
spring.datasource.url=jdbc:h2:mem:userdb
spring.datasource.username=sa
spring.datasource.password=pwd
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

rsa.rsa-private-key=classpath:certs/private.pem
rsa.rsa-public-key=classpath:certs/public.pem