package com.assessment.tracker.server.utils.enums;

public enum AssessmentProgress {
    CREATED,
    CHECKED,
    NEEDS_CHANGES,
    EXAMS_OFFICER_CHECK,
    NEEDS_CHANGES_2,
    EXTERNAL_EXAMINER_CHECK,
    SETTER_FORMAL_RESPONSE,
    SPEC_RELEASED,
    TAKING_PLACE,
    MARKING_STANDARDISED,
    MARKED,
    CHECKED_BY_ADMIN,
    MARKING_MODERATED,
    RESULTS_RETURNED,
    COMPLETE
}
