package com.assessment.tracker.server.persistence.user;

import com.assessment.tracker.server.persistence.assignedusers.AssignedUser;
import jakarta.persistence.*;
import java.util.*;

@Entity
@Table(name = "users")

//table for users, refer to data design doc for reference
public class User {

    //first section for generating columns
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public int userID; //primary key
    //UUID

    @OneToMany
    private Set<AssignedUser> assignedUsers = new HashSet<>();

    @Column(nullable = false, unique = true)
    private String username;

    @Column(nullable = false, unique = true)
    private String email;//format verification?

    @Column(nullable = false, unique = true)
    private String password; //required encryption

    //constructors
    public User(String username, String email, String Password ) {
        this.username = username;
        this.password = Password;
        this.email = email;
    }
    public User() {
    }

    //the following section for getters and setter (auto-generated by IDE)
    public void setUserID(int userID) {
        this.userID = userID;
    }
    public int getUserID() {
        return userID;
    }

    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }



}
