package com.assessment.tracker.server.persistence.user;

import com.assessment.tracker.server.persistence.assignedusers.AssignedUser;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import org.springframework.beans.factory.annotation.Autowired;

import java.beans.BeanProperty;
import java.util.*;
import com.assessment.tracker.server.api.assessment.*;


@Entity
@Table(name = "users")

// table for users, refer to data design doc for reference
public class User {

    // first section for generating columns
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID userID; //primary key

    @OneToMany
    private Set<AssignedUser> assignedUsers = new HashSet<>();

    @Column(nullable = false, unique = true)
    private String username;

    @Column(nullable = false, unique = true)
    private String email;// format verification?

    @JsonIgnore
    @Column(nullable = false, unique = true)
    private String password; // required encryption

    @OneToMany(mappedBy = "setter")
    private List<Assessment> setterFor;

    @OneToMany(mappedBy = "checker")
    private List<Assessment> checkerFor;


    public enum userType{
        TEACHING_SUPPORT,
        ACADEMIC,
        EXTERNAL_EXAMINER,
        EXAMS_OFFICER
    }

    @Column(nullable = false, unique = false)
    private userType userType;

    //constructors
    public User(String username, String email, String Password, userType userType ) {
        this.username = username;
        this.password = Password;
        this.email = email;
        this.userType = userType;
    }

    public User() {
    }

    //the following section for getters and setter (auto-generated by IDE)
    public void setUserID(UUID userID) {
        this.userID = userID;
    }
    public UUID getUserID() {
        return userID;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public userType getUserType() {
        return userType;
    }
    public void setUserType(userType userType) {
        this.userType = userType;
    }



}
