package com.assessment.tracker.server.persistence;

import jakarta.persistence.*;

@Entity
@Table(name = "users")

//table for users, refer to data design doc for reference
public class User {

    //first section for generating columns
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long userID; //primary key

    private String username;
    private String email;//format verification?
    private String password; //required encryption
    private Role role;

    //constructors
    public User(String username, String Password ) {
        this.username = username;
    }
    public User() {
    }

    //following section for getters and setter (auto-generated by IDE)
    public void setUserID(Long userID) {
        this.userID = userID;
    }
    public Long getUserID() {
        return userID;
    }
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }

    public Role getRole() {
        return role;
    }
    public void setRole(Role role) {
        this.role = role;
    }
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
}
